### PR TITLE
Update PKGBUILD b2sum for LICENSE file

### PR DESCRIPTION
**Pull request by CasAdair**

### CODE REVIEW

**Comment by jamescherti** [comment]
Thank you for the pull request!

**Comment by jamescherti** [comment]
Could you please try and confirm that the new version is working, @LilithLaw:
1. AUR version: https://aur.archlinux.org/packages/linux-keep-modules
2. GitHub version: https://github.com/jamescherti/archlinux-linux-keep-modules

Thanks.

**Comment by CasAdair** [comment]
It seems to build successfully and install now! Sorry life has been busy.

**Comment by jamescherti** [comment]
Thank you for confirming, @LilithLaw!

**Pull request merged**
